'use client';
import {useEffect,useMemo,useState} from 'react';
import catalog from '@/lib/catalog';
import {identityFor,normalizeGTIN,duplicateCandidates,coverageCount} from '@/lib/catalog-reliability';
import {inventoryStatus} from '@/lib/collection-details';
import audits from '@/lib/catalog-audits.json';
import {requestJSON} from '@/lib/api-client';
import {CatalogIssueForm} from '@/components/catalog-evidence';
import {ZoomableImage} from '@/components/zoomable-image';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
const lines=[...new Set(catalog.map(r=>r.line))],years=[...new Set(catalog.map(r=>r.year))].sort((a,b)=>a-b);
export default function CatalogHealth(){
 const [line,setLine]=useState('All lines'),[year,setYear]=useState('All years'),[issues,setIssues]=useState<any[]>([]),[checks,setChecks]=useState<any[]>([]),[canEdit,setCanEdit]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[limit,setLimit]=useState(100),[notes,setNotes]=useState<Record<string,string>>({});
 const [check,setCheck]=useState({line:lines[0],year:1984,basis:'Figure versions',source:'',expected:'',note:'',status:'Needs review'});
 const candidates=useMemo(()=>duplicateCandidates(catalog),[]);
 async function load(){try{const access=await requestJSON('/api/collection',{},true);setCanEdit(access.canEdit===true);if(access.canEdit){const data=await requestJSON('/api/catalog-review',{},true);setIssues(data.issues);setChecks(data.checks);}setMessage('');}catch(e:any){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 const rows=catalog.filter(r=>(line==='All lines'||r.line===line)&&(year==='All years'||r.year===Number(year)));
 const groups=new Map<string,any>();for(const r of rows){const key=r.line+'~'+r.year;const g=groups.get(key)||{line:r.line,year:r.year,total:0,verified:0,reviewed:0,partial:0,unverified:0};g.total++;if(identityFor(r).status==='verified')g.verified++;g[inventoryStatus(r.id)]++;groups.set(key,g);}
 const summaries=[...groups.values()].sort((a,b)=>a.line.localeCompare(b.line)||a.year-b.year);
 const ids=new Set(rows.map(r=>r.id)),filteredCandidates=candidates.filter(c=>ids.has(c.left.id)||ids.has(c.right.id));
 const valid=catalog.filter(r=>normalizeGTIN(r.upc)).length,invalid=catalog.filter(r=>r.upc&&!normalizeGTIN(r.upc));
 async function post(body:any){setBusy(true);try{const result=await requestJSON('/api/catalog-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},true);await load();return result;}catch(e:any){setMessage(e.message);return null;}finally{setBusy(false);}}
 return <main className="coverage-page"><a href="/">Back to the Armory</a><h1>Catalog health</h1><p>Release identity, accessory completeness, and source-index coverage are separate checks. Imported records remain partial until reviewed; equal counts alone do not prove complete coverage.</p><div className="stats"><div><span>CATALOG ENTRIES</span><strong>{catalog.length}</strong><small>{catalog.filter(r=>identityFor(r).status==='verified').length} verified identities</small></div><div><span>VALID BARCODE FORMATS</span><strong>{valid}</strong><small>{invalid.length} require review; validity does not prove identity</small></div><div><span>DUPLICATE CANDIDATES</span><strong>{candidates.length}</strong><small>No automatic merges</small></div><div><span>RECONCILED AUDITS</span><strong>{audits.length+checks.filter(c=>c.status==='Reconciled'&&coverageCount(catalog,c)===c.catalogCount).length}</strong><small>Limited to each explicitly described scope</small></div></div><div className="coverage-filters"><select aria-label="Toy line" value={line} onChange={e=>{setLine(e.target.value);setLimit(100);}}>{['All lines',...lines].map(l=><option key={l}>{l}</option>)}</select><select aria-label="Year" value={year} onChange={e=>{setYear(e.target.value);setLimit(100);}}>{['All years',...years.map(String)].map(y=><option key={y}>{y}</option>)}</select></div>{message&&<div className="notice" role="alert">{message} <button onClick={load}>Retry loading</button></div>}{!canEdit&&<p>Reviews are private to the owner. <a href="https://jeffs-joe-armory.jfattic.chatgpt.site/signin-with-chatgpt?return_to=/catalog-health" target="_blank" rel="noreferrer">Sign in</a> then <button onClick={load}>Check access again</button>.</p>}<Tabs defaultValue="coverage"><TabsList><TabsTrigger value="coverage">Coverage</TabsTrigger><TabsTrigger value="duplicates">Duplicates</TabsTrigger><TabsTrigger value="issues">Review queue</TabsTrigger></TabsList>
 <TabsContent value="coverage"><h2>Checks by line and year</h2><div className="coverage-table"><table><thead><tr><th>Line / year</th><th>Entries</th><th>Verified identities</th><th>Reviewed parts</th><th>Partial parts</th><th>No sourced parts</th><th>Source-index audit</th></tr></thead><tbody>{summaries.map(g=>{const latest=checks.filter(c=>c.line===g.line&&c.year===g.year).sort((a,b)=>b.checked.localeCompare(a.checked))[0];return <tr key={g.line+g.year}><td>{g.line} · {g.year}</td><td>{g.total}</td><td>{g.verified}</td><td>{g.reviewed}</td><td>{g.partial}</td><td>{g.unverified}</td><td>{latest?(latest.catalogCount!==coverageCount(catalog,latest)?'Catalog changed; recheck required':latest.status)+' · '+latest.basis:'Not audited'}</td></tr>;})}</tbody></table></div><h2>Recorded audits</h2>{audits.map(a=><article className="audit-card" key={a.id}><h3>{a.name}</h3><p>{a.status} · {a.expected} expected versions · {a.releaseIds.filter(id=>catalog.some(r=>r.id===id)).length} represented · {a.checked}</p><p>{a.note}</p><a href={a.source} target="_blank" rel="noreferrer">Archive index evidence</a><ul>{a.releaseIds.map(id=><li key={id}><a href={'/?release='+id}>{catalog.find(r=>r.id===id)?.name}</a></li>)}</ul></article>)}{checks.map(c=><article className="audit-card" key={c.id}><h3>{c.line} · {c.year} · {c.basis}</h3><p>{c.status} · source expected {c.expected} · catalog when checked {c.catalogCount} · current {coverageCount(catalog,c)} · {c.checked.slice(0,10)}</p><p>{c.note}</p><a href={c.source} target="_blank" rel="noreferrer">Source index</a></article>)}
 <details><summary>Record a source-index audit</summary><p>Compare actual entries with the index using the same counting basis. Record exclusions and unresolved differences. Mark reconciled only after reviewing every expected entry.</p><div className="formgrid"><label>Line<select disabled={!canEdit} value={check.line} onChange={e=>setCheck(c=>({...c,line:e.target.value}))}>{lines.map(l=><option key={l}>{l}</option>)}</select></label><label>Year<input disabled={!canEdit} type="number" value={check.year} onChange={e=>setCheck(c=>({...c,year:Number(e.target.value)}))}/></label><label>Counting basis<select disabled={!canEdit} value={check.basis} onChange={e=>setCheck(c=>({...c,basis:e.target.value}))}>{['Figure versions','Retail packages and vehicles','All catalog items'].map(b=><option key={b}>{b}</option>)}</select></label><label>Expected source count<input disabled={!canEdit} type="number" min="0" value={check.expected} onChange={e=>setCheck(c=>({...c,expected:e.target.value}))}/></label><label className="wide">Source index URL<input disabled={!canEdit} type="url" value={check.source} onChange={e=>setCheck(c=>({...c,source:e.target.value}))}/></label><label className="wide">Compared entries, exclusions and unresolved differences<textarea disabled={!canEdit} value={check.note} onChange={e=>setCheck(c=>({...c,note:e.target.value}))}/></label><label>Status<select disabled={!canEdit} value={check.status} onChange={e=>setCheck(c=>({...c,status:e.target.value}))}><option>Needs review</option><option>Reconciled</option></select></label></div><p>Current catalog count for this basis: {coverageCount(catalog,check)}</p><button disabled={!canEdit||busy||check.expected===''||!check.note.trim()||!check.source.trim()||(check.status==='Reconciled'&&Number(check.expected)!==coverageCount(catalog,check))} onClick={async()=>{const result=await post({action:'check',check:{...check,expected:Number(check.expected)}});if(result)setMessage('Audit saved.');}}>Save audit</button></details>
 <h2>Release evidence</h2><div className="coverage-table"><table><thead><tr><th>Release</th><th>Identity</th><th>Type</th><th>Parts</th><th>Source</th></tr></thead><tbody>{rows.slice(0,limit).map(r=><tr key={r.id}><td><a href={'/?release='+r.id}>{r.year} {r.name}</a></td><td>{identityFor(r).status}</td><td>{identityFor(r).entityType}</td><td>{inventoryStatus(r.id)}</td><td><a href={r.url} target="_blank" rel="noreferrer">Reference</a> · {r.checked}</td></tr>)}</tbody></table></div>{rows.length>limit&&<button onClick={()=>setLimit(n=>n+100)}>Show more</button>}<a href="/accessory-coverage">Detailed accessory coverage</a></TabsContent>
 <TabsContent value="duplicates"><h2>Review possible duplicates</h2><p>GTINs are normalized with leading zeroes and validated by check digit. Retailer SKUs are compared only within the same issuer. Similar names are weaker evidence. A figure and its package can legitimately share information.</p>{filteredCandidates.slice(0,60).map(c=>{const issue=issues.find(i=>i.context===c.id);return <article className="audit-card" key={c.id}><h3>{c.reason}</h3><p>{c.evidence}</p><div className="candidate-grid">{[c.left,c.right].map((r:any)=><div key={r.id}><a href={'/?release='+r.id}>{r.name} · {r.year} · {r.line}</a><p>{identityFor(r).entityType} · barcode {r.upc||'Unknown'} · SKU {r.sku||'Unknown'}</p><a href={r.url} target="_blank" rel="noreferrer">Source record</a></div>)}</div><p>{c.needsReview}</p>{issue?<p>Review: {issue.status} · {issue.reviewNote||'No review note yet'}</p>:<button disabled={!canEdit||busy} onClick={()=>post({action:'issue',issue:{type:'Duplicate',releaseId:c.left.id,details:`Compare ${c.left.name} (${c.left.id}) and ${c.right.name} (${c.right.id}). ${c.reason}. ${c.needsReview}`,source:c.left.url,context:c.id,photos:[]}})}>Add pair to review queue</button>}</article>;})}<p>{filteredCandidates.length} candidates in this filter{filteredCandidates.length>60?' · first 60 shown; narrow the filters':''}. Decisions do not automatically merge or delete owned items.</p>{invalid.length>0&&<details><summary>{invalid.length} invalid barcode formats</summary>{invalid.map(r=><p key={r.id}><a href={'/?release='+r.id}>{r.name}</a> · {r.upc}</p>)}</details>}</TabsContent>
 <TabsContent value="issues"><h2>Private review queue</h2><CatalogIssueForm disabled={!canEdit}/><button onClick={load}>Refresh queue</button>{!issues.length&&<p>No reports loaded. Report problems from any dossier, including an unidentified item.</p>}{issues.sort((a,b)=>b.created.localeCompare(a.created)).map(i=><article className="audit-card" key={i.id}><h3>{i.type} · {i.status}</h3><p>{i.created.slice(0,10)} · {i.context}</p>{i.releaseId&&<a href={'/?release='+i.releaseId}>Open catalog dossier</a>} {i.itemId&&<a href={'/?item='+encodeURIComponent(i.itemId)}>Open owned item</a>}<p className="preserve-lines">{i.details}</p>{i.source&&<a href={i.source} target="_blank" rel="noreferrer">Supporting source</a>}<div className="owner-photo-grid">{i.photos?.map((src:string)=><ZoomableImage key={src} src={src} title="Issue evidence"/>)}</div><p>{i.reviewNote}</p><label>Review findings / resolution<textarea disabled={!canEdit} value={notes[i.id]??i.reviewNote??''} onChange={e=>setNotes(n=>({...n,[i.id]:e.target.value}))}/></label><div className="photo-tools">{['Open','Investigating','Resolved','Distinct releases'].map(status=><button key={status} disabled={!canEdit||busy||((status==='Resolved'||status==='Distinct releases')&&!(notes[i.id]??i.reviewNote)?.trim())} onClick={()=>post({action:'review',id:i.id,status,note:notes[i.id]??i.reviewNote??''})}>{status}</button>)}</div><p>Review status records findings. It does not silently rewrite source facts or remove collection records.</p></article>)}</TabsContent></Tabs></main>;
}
