'use client';
import {useState} from 'react';
import catalog from '@/lib/catalog';
import {identityFor,normalizeGTIN} from '@/lib/catalog-reliability';
import {knownPieces,mergeKnownPieces} from '@/lib/collection-details';
import {linkItem} from '@/lib/catalog-reliability';
import {Command,CommandInput,CommandList,CommandEmpty,CommandItem} from '@/components/ui/command';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {requestJSON} from '@/lib/api-client';
import {ZoomableImage} from '@/components/zoomable-image';
export function CatalogEvidence({release}:{release:any}){
 const identity=identityFor(release);return <section className="catalog-evidence"><h3>Catalog evidence</h3><p><strong>{identity.status==='verified'?'Verified release identity':release?'Partial information':'Unidentified item'}</strong> · {identity.entityType} · {identity.version} · {identity.scale}</p><p>{release?identity.status==='verified'?'The exact archive version has been checked. Accessory coverage is assessed separately.':'Imported reference. Version, contents, and packaging relationships have not been fully reconciled.':'Save photos and markings now. Link to an exact release when identified.'}</p>{identity.packageNote&&<p>{identity.packageNote}</p>}{identity.related.length>0&&<ul>{identity.related.map((link:any)=><li key={link.id}>{link.role}: <a href={'/?release='+encodeURIComponent(link.id)} target="_blank" rel="noreferrer">{catalog.find(r=>r.id===link.id)?.name||link.id}</a></li>)}</ul>}{identity.conflicts.map((conflict:any)=><div className="notice" key={conflict.field}><strong>Unresolved {conflict.field} conflict</strong>{conflict.values.map((v:any)=><p key={String(v.value)}><a href={v.source} target="_blank" rel="noreferrer">{String(v.value)} · source</a></p>)}</div>)}{release&&<><p>GTIN: {release.upc||'Not recorded'}{release.upc?' · '+(normalizeGTIN(release.upc)?'Check digit valid; product match still requires evidence':'Invalid format or check digit; requires review'):''}. SKU: {release.sku||'Not recorded'} {release.skuRetailer||release.retailer||release.skuIssuer||''}</p><p>These sources describe the catalog reference. Owner-entered fields remain your observations until reviewed.</p><details><summary>Reference field sources and verification dates</summary><div className="coverage-table"><table><thead><tr><th>Field</th><th>Value</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{Object.entries(identity.fields).map(([field,e]:any)=><tr key={field}><td>{field}</td><td>{String(field==='version'?identity.version:release[field]??'See source')}</td><td>{e.status}</td><td><a href={e.source} target="_blank" rel="noreferrer">Source</a> · {e.checked||'Date unknown'}</td></tr>)}</tbody></table></div>{identity.sources.map((s:any)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a> · {s.sourceId} · {s.checked}</p>)}</details></>}</section>;
}
export function ReleaseLinker({item,disabled,onLink}:{item:any;disabled:boolean;onLink:(item:any)=>void}){
 const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState<any>(null);
 const choices=search.trim()?catalog.filter(r=>`${r.name} ${r.year} ${r.line} ${r.upc||''}`.toLowerCase().includes(search.toLowerCase())).slice(0,40):[];
 return <><button type="button" className="outline" disabled={disabled} onClick={()=>{setSelected(null);setSearch(item.name||'');setOpen(true);}}>{item.releaseId?'Change catalog match':'Identify / link to catalog'}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="identity-dialog"><DialogTitle>Match this item to a release</DialogTitle><DialogDescription>Your photos, counts, condition and notes stay with this item. Previously confirmed sales and price adjustments need review after a new match.</DialogDescription><Command shouldFilter={false}><CommandInput placeholder="Search name, year, line or barcode" value={search} onValueChange={setSearch}/><CommandList><CommandEmpty>Search for a release. If it is absent, keep the item unidentified and report the missing release.</CommandEmpty>{choices.map(r=><CommandItem key={r.id} value={r.id} onSelect={()=>setSelected(r)}>{r.name} · {r.year} · {r.line} · {identityFor(r).entityType}</CommandItem>)}</CommandList></Command>{choices.length===40&&<p>First 40 matches. Narrow the search by name or barcode.</p>}{selected&&<><CatalogEvidence release={selected}/><button type="button" className="primary" disabled={disabled} onClick={()=>{const list=knownPieces(selected.id);onLink(linkItem(item,selected,mergeKnownPieces(item.pieces||[],list?.pieces||[],list?.source)));setOpen(false);}}>Use {selected.name}</button></>}</DialogContent></Dialog></>;
}
export function CatalogIssueForm({releaseId,itemId,photos=[],disabled=false,context=''}:{releaseId?:string;itemId?:string;photos?:string[];disabled?:boolean;context?:string}){
 const [open,setOpen]=useState(false),[type,setType]=useState('Missing part'),[details,setDetails]=useState(''),[source,setSource]=useState(''),[attachments,setAttachments]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <section className="catalog-issue"><button type="button" className="outline" disabled={disabled} onClick={()=>{setAttachments(photos);setMessage('');setOpen(true);}}>Report a catalog problem</button> <a href="/catalog-health">View coverage and review queue</a><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="identity-dialog"><DialogTitle>Report a catalog problem</DialogTitle><DialogDescription>Save evidence in your private review queue. Reporting a problem does not change your owned item or mark the catalog verified.</DialogDescription><label>Problem type<select value={type} onChange={e=>setType(e.target.value)}>{['Missing release','Missing part','Wrong image','Duplicate','Incorrect identity','Source conflict','Other'].map(t=><option key={t}>{t}</option>)}</select></label><label>Details<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="What is missing or incorrect? Include version, markings and expected parts." maxLength={6000}/></label><label>Supporting source URL<input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://…"/></label><label>Attach evidence photos<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy||disabled} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);try{for(const file of files){const body=new FormData();body.append('file',file);const result=await requestJSON('/api/photo',{method:'POST',body});setAttachments(a=>[...a,result.url]);}}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}/></label><div className="owner-photo-grid">{attachments.map((src,index)=><div key={src}><ZoomableImage src={src} title={'Evidence photo '+(index+1)}/><button type="button" disabled={busy} onClick={()=>setAttachments(a=>a.filter((_,i)=>i!==index))}>Exclude photo</button></div>)}</div>{message&&<p role="status">{message}</p>}<button type="button" className="primary" disabled={disabled||busy||!details.trim()} onClick={async()=>{setBusy(true);try{await requestJSON('/api/catalog-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'issue',issue:{releaseId,itemId,type,details,source,photos:attachments,context}})});setMessage('Report saved. View it in the review queue.');setDetails('');setSource('');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>{busy?'Working…':'Save report'}</button><a href="/catalog-health">Open review queue</a></DialogContent></Dialog></section>;
}
export function SourceVersionCheck({release,disabled}:{release:any;disabled:boolean}){
 const [result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <section className="catalog-evidence"><h3>Check this character’s archive versions</h3><p>Compare exact source links with our catalog to expose omitted or unlinked versions.</p><button type="button" className="outline" disabled={disabled||busy} onClick={async()=>{setBusy(true);setMessage('');try{setResult(await requestJSON('/api/related-versions?id='+encodeURIComponent(release.id),{},true));}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>{busy?'Checking source index…':'Check archive versions'}</button>{message&&<p role="status">{message}</p>}{result&&<><p>{result.note} Checked {result.checked.slice(0,10)}.</p><div className="coverage-table"><table><thead><tr><th>Version</th><th>Catalog match</th><th>Action</th></tr></thead><tbody>{result.versions.map((v:any)=><tr key={v.url}><td><a href={v.url} target="_blank" rel="noreferrer">{v.label}</a></td><td>{v.status}</td><td>{v.releaseId?<a href={'/?release='+v.releaseId} target="_blank" rel="noreferrer">Open dossier</a>:<button type="button" disabled={disabled||busy} onClick={async()=>{setBusy(true);try{await requestJSON('/api/catalog-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'issue',issue:{type:'Missing release',details:`Archive version ${v.label} has no exact catalog mapping. Check existing records before importing.`,source:v.url,context:v.label,photos:[]}})},true);setMessage('Version added to the review queue.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>Flag missing / unlinked version</button>}</td></tr>)}</tbody></table></div></>}</section>;
}
