'use client';
import {useEffect,useRef,useState,useId} from 'react';
import {ZoomableImage} from '@/components/zoomable-image';
import {Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function CollectionPhoto({photos,disabled,onUpload,onRemove,onCover,onWorkingChange}:{photos:string[];disabled:boolean;onWorkingChange?:(busy:boolean)=>void;onUpload:(file:File)=>Promise<void>;onRemove:(index:number)=>void;onCover:(index:number)=>void}){
 const fileInputId=useId();
 const [open,setOpen]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[working,setWorking]=useState(false),[filename,setFilename]=useState('');
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);
 const close=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setOpen(false);setReady(false);};
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());},[]);
 useEffect(()=>{if(!open)return;let canceled=false;setReady(false);setError('');(async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is unavailable in this browser. Choose a local image file instead.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(canceled){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play();setReady(true);}}catch(e:any){if(!canceled)setError(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser or choose a local image file.':e.name==='NotFoundError'?'No camera was found. Choose a local image file instead.':'The camera could not start. Choose a local image file instead.');}})();return()=>{canceled=true;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};},[open]);
 const upload=async(files:File[])=>{if(files.length>10-photos.length){setError('Choose at most '+(10-photos.length)+' more images.');return;}setError('');setWorking(true);onWorkingChange?.(true);const failures:string[]=[];try{for(const [index,file] of files.entries()){setFilename(`${index+1} of ${files.length}: ${file.name}`);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){failures.push(file.name+': choose a JPG, PNG or WebP under 8 MB.');continue;}try{await onUpload(file);}catch(e:any){failures.push(file.name+': '+(e.message||'Upload failed.'));}}}finally{setWorking(false);onWorkingChange?.(false);setError(failures.join(' '));}};
 return <section className="collection-photo"><h3>Your collection photos</h3><p>Add views of your copy, packaging and accessories. Photos are saved when you save the item.</p><label htmlFor={fileInputId}>Choose one or more images</label><input id={fileInputId} type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={disabled||working} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)await upload(files);}}/><div className="photo-tools"><button type="button" className="outline" disabled={disabled||working} onClick={()=>setOpen(true)}><Camera size={18}/> Use camera</button><span>JPG, PNG or WebP · up to 8 MB</span></div>{working&&<p role="status">Uploading {filename}…</p>}{error&&!open&&<p role="alert" className="notice">{error}</p>}<div className="owner-photo-grid">{photos.map((src,index)=><div className="owner-photo-card" key={src}><ZoomableImage src={src} title={index===0?'Your cover photo':`Your photo ${index+1}`}/><div className="photo-card-actions">{index===0?<span>Cover photo</span>:<button type="button" className="outline" disabled={disabled||working} onClick={()=>onCover(index)}>Make cover</button>}<button type="button" className="danger" aria-label={'Remove photo '+(index+1)+' from item'} disabled={disabled||working} onClick={()=>onRemove(index)}>Remove from item</button></div></div>)}</div><Dialog open={open} onOpenChange={value=>{if(!value)close();}}><DialogContent className="camera-dialog"><DialogTitle>Photograph your item</DialogTitle><DialogDescription>Allow camera access, frame your item, then take a photo.</DialogDescription><video ref={element=>{video.current=element;if(element&&stream.current){element.srcObject=stream.current;void element.play().then(()=>setReady(true)).catch(()=>setError('The camera preview could not start. Choose a local image file instead.'));}}} autoPlay muted playsInline/>{!ready&&!error&&<p role="status">Allow camera access in your browser to start the preview.</p>}{error&&<p role="alert" className="notice">{error}</p>}<div className="camera-actions"><button type="button" className="outline" onClick={close}>Cancel</button><button type="button" className="primary" disabled={!ready||working||disabled} onClick={async()=>{const v=video.current;if(!v?.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;canvas.getContext('2d')!.drawImage(v,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(blob){close();await upload([new File([blob],'collection-camera.jpg',{type:'image/jpeg'})]);}}}>Take photo</button></div></DialogContent></Dialog></section>;
}
