'use client';
import {useEffect,useState} from 'react';
import {Expand,Minus,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function ZoomableImage({src,fullSrc,title,source,credit,fallback}:{src:string;fullSrc?:string;title:string;source?:string;credit?:string;fallback?:string}){
 const [open,setOpen]=useState(false),[zoom,setZoom]=useState(1),[failed,setFailed]=useState(false),[largeFailed,setLargeFailed]=useState(false),[largeLoaded,setLargeLoaded]=useState(false),[preview,setPreview]=useState(src);
 useEffect(()=>{setPreview(src);setFailed(false);setLargeFailed(false);setOpen(false);},[src]);
 const enlarge=()=>{setZoom(1);setLargeFailed(false);setLargeLoaded(false);setOpen(true);};
 return <figure className="zoomable-photo"><div className="image-topbar"><span>{title}</span><a href={fullSrc||preview} role="button" aria-haspopup="dialog" aria-label={'Enlarge '+title} className="outline" onClick={e=>{e.preventDefault();enlarge();}} onKeyDown={e=>{if(e.key===' '){e.preventDefault();enlarge();}}}><Expand size={16}/> Enlarge</a></div>{failed?<div className="photo-unavailable">Photo unavailable{source&&<a href={source} target="_blank" rel="noreferrer">View source photos</a>}</div>:<img src={preview} alt={title} loading="lazy" onError={()=>{if(fallback&&preview!==fallback)setPreview(fallback);else setFailed(true);}}/>}{(source||credit)&&<figcaption>{credit&&<span>{credit} · </span>}{source&&<a href={source} target="_blank" rel="noreferrer">Photo source</a>}</figcaption>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="image-viewer"><DialogTitle>{title}</DialogTitle><DialogDescription>Use zoom to inspect details. Scroll to move around the enlarged photo.</DialogDescription><div className="image-zoom-controls"><button type="button" className="outline" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.5))} aria-label="Zoom out"><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button type="button" className="outline" disabled={zoom>=4} onClick={()=>setZoom(z=>Math.min(4,z+.5))} aria-label="Zoom in"><Plus size={18}/></button><button type="button" className="outline" onClick={()=>setZoom(1)}>Fit</button><a href={fullSrc||preview} target="_blank" rel="noreferrer">Open original</a></div><div className="image-viewer-scroll">{!largeLoaded&&<p role="status">Loading full-size image…</p>}<img src={largeFailed?preview:fullSrc||preview} alt={title} style={{width:`${zoom*100}%`,maxWidth:'none'}} onLoad={()=>setLargeLoaded(true)} onError={()=>{setLargeFailed(true);setLargeLoaded(true);}}/></div>{largeFailed&&<p>Original image unavailable; showing the preview.</p>}{source&&<p><a href={source} target="_blank" rel="noreferrer">View source</a>{credit?' · '+credit:''}</p>}</DialogContent></Dialog></figure>;
}
