'use client';
import { useEffect, useState } from 'react';
import { LaunchShell, useLaunchAccount, AccessNotice } from '@/components/launch-shell';
import { requestJSON } from '@/lib/api-client';
import { ZoomableImage } from '@/components/zoomable-image';
export default function Collectors() {
    const { account, error } = useLaunchAccount(), [query, setQuery] = useState(''), [offset, setOffset] = useState(0), [data, setData] = useState<any>(null), [status, setStatus] = useState('');
    useEffect(() => { if (!account)
        return; const controller = new AbortController(); const params = new URLSearchParams(window.location.search); const id = params.get('collectionId'); setData(null); setStatus('Loading…'); requestJSON<any>(id ? '/api/collection?collectionId=' + encodeURIComponent(id) : '/api/collectors?q=' + encodeURIComponent(query) + '&offset=' + offset, { signal: controller.signal }).then(r => { setData(r); setStatus(''); }).catch(e => { if (!controller.signal.aborted)
        setStatus(e.message); }); return () => controller.abort(); }, [account, query, offset]);
    return <LaunchShell title={data?.collection ? data.collection.displayName + "'s collection" : 'Public collections'}>{!account ? <AccessNotice error={error}/> : <><p>Collections marked public are visible to signed-in collectors. Private owners are never listed.</p>{!data?.collection && <label className="search">Search display names<input value={query} onChange={e => { setQuery(e.target.value); setOffset(0); }}/></label>}<p role="status">{status}</p>{data?.collections && <><section className="collection-grid">{data.collections.map((c: any) => <article className="card" key={c.id}><div className="cardbody"><h2>{c.display_name}</h2><p>{c.records} collection records</p><a href={'/collectors?collectionId=' + encodeURIComponent(c.id)}>View collection</a></div></article>)}</section>{!data.collections.length && <p>No matching public collections.</p>}<div className="pagination"><button className="outline" disabled={!offset} onClick={() => setOffset(n => Math.max(0, n - 48))}>Previous</button><button className="outline" disabled={data.collections.length < 48} onClick={() => setOffset(n => n + 48)}>Next</button></div></>}{data?.items && <><a href="/collectors">All public collections</a>{!data.items.length && <p>No collection records yet.</p>}<section className="collection-grid">{data.items.map((e: any) => <article className="card" key={e.id}><div className="cardbody"><h2>{e.name}</h2><p>{e.condition} · {e.completeness} · {e.ownership.replaceAll('_', ' ')}</p><p>Packaging: {e.packaging} · Sealed: {e.sealed === null ? 'unknown' : e.sealed ? 'yes' : 'no'}</p>{e.releaseId && <a href={'/?release=' + encodeURIComponent(e.releaseId)}>Reference release</a>}<details><summary>Parts & condition</summary><ul>{e.parts.map((p: any) => <li key={p.partId}>{p.label}: {p.quantity ?? 'unknown'} · {p.condition ?? 'ungraded'} {p.defects}</li>)}{e.unidentifiedParts.map((p: any, i: number) => <li key={i}>{p.name}: {p.quantity ?? 'unknown'} · {p.condition ?? 'ungraded'} {p.defects}</li>)}</ul></details><div className="owner-photo-grid">{e.photos.map((url: string) => <ZoomableImage key={url} src={url} title={e.name}/>)}</div></div></article>)}</section></>}</>}</LaunchShell>;
}
