'use client';
import {useState} from 'react';
import catalog from '@/lib/catalog';
import {inventoryStatus,inventoryLabel,knownPieces} from '@/lib/collection-details';
export default function Coverage(){
 const [line,setLine]=useState('All lines'),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(100);
 const lines=[...new Set(catalog.map(r=>r.line))];
 const filtered=catalog.filter(r=>(line==='All lines'||r.line===line)&&(status==='all'||inventoryStatus(r.id)===status)&&`${r.name} ${r.year}`.toLowerCase().includes(query.toLowerCase()));
 const summary=lines.map(line=>{const rows=catalog.filter(r=>r.line===line);return {line,total:rows.length,reviewed:rows.filter(r=>inventoryStatus(r.id)==='reviewed').length,partial:rows.filter(r=>inventoryStatus(r.id)==='partial').length,unverified:rows.filter(r=>inventoryStatus(r.id)==='unverified').length};});
 return <main className="coverage-page"><a href="/">Back to the Armory</a><h1>Accessory inventory coverage</h1><p>Reviewed inventories have been checked against the release source. Partial inventories contain sourced gear but may omit paperwork, small parts or vehicle subassemblies. Unverified releases have no sourced contents list. These statuses describe catalog coverage, not whether you own every piece.</p><div className="coverage-table"><table><thead><tr><th>Toy line</th><th>Releases</th><th>Reviewed</th><th>Partial</th><th>Unverified</th></tr></thead><tbody>{summary.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.total}</td><td>{r.reviewed}</td><td>{r.partial}</td><td>{r.unverified}</td></tr>)}</tbody></table></div><h2>Find an inventory</h2><div className="coverage-filters"><input aria-label="Search inventories" placeholder="Name or year" value={query} onChange={e=>{setQuery(e.target.value);setLimit(100);}}/><select aria-label="Toy line" value={line} onChange={e=>{setLine(e.target.value);setLimit(100);}}>{['All lines',...lines].map(l=><option key={l}>{l}</option>)}</select><select aria-label="Inventory status" value={status} onChange={e=>{setStatus(e.target.value);setLimit(100);}}><option value="all">All statuses</option><option value="unverified">Unverified</option><option value="partial">Partial sourced inventory</option><option value="reviewed">Reviewed inventory</option></select></div><p>{filtered.length} releases</p><div className="coverage-table"><table><thead><tr><th>Release</th><th>Line</th><th>Status</th><th>Checklist entries</th><th>Source</th></tr></thead><tbody>{filtered.slice(0,limit).map(r=>{const list=knownPieces(r.id);return <tr key={r.id}><td><a href={'/?release='+encodeURIComponent(r.id)}>{r.year} {r.name}</a></td><td>{r.line}</td><td>{inventoryLabel(r.id)}</td><td>{list?list.pieces.length:'Unknown'}</td><td>{list&&<a href={list.source} target="_blank" rel="noreferrer">Reference · {list.checked||'Date unknown'}</a>}</td></tr>;})}</tbody></table></div>{filtered.length>limit&&<button onClick={()=>setLimit(n=>n+100)}>Show more</button>}</main>;
}
